# Database related settings
database-uri: "jdbc:mysql://localhost:3306/minecraft?useSSL=false&autoReconnect=true"
database-username: "root"
database-password: "password"

server-name: "default"
override-bed-respawn-location: false
override-anchor-respawn-location: false
