name: FluffyTeams
main: fr.fluffevent.fluffyteams.FluffyTeams
version: 0.0.1-SNAPSHOT
api-version: 1.20
author: FluffEvent
authors: [lululombard]
website: fluffevent.fr
commands:
  fluffyteams:
    description: Fluffy teams commands
    usage: /fluffyteams
    permission: fluffyteams.admin
