name: FluffyTeams
main: fr.fluffevent.fluffyteams.FluffyTeams
version: 0.0.1-SNAPSHOT
api-version: 1.20
author: RedCraft
authors: [TestUser]
website: redcraft.org
commands:
  test:
    description: Test command
    usage: /test
    permission: fluffyteams.test
