name: FluffyTeams
main: fr.fluffevent.fluffyteams.FluffyTeams
version: 0.1.1-SNAPSHOT
api-version: 1.21
author: FluffEvent
authors: [lululombard]
website: fluffevent.fr
commands:
  fluffyteams:
    aliases: [ft]
    description: Fluffy teams commands
    usage: /fluffyteams
    permission: fluffyteams.admin
